SET PATH=C:\users\rahulba\AppData\Local\Keil_v5\ARM\BIN41;C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\WindowsPowershell\v1.0
SET RVCT0INC=C:\users\rahulba\AppData\Local\Keil_v5\ARM\RV31\Inc
SET RVCT0LIB=C:\users\rahulba\AppData\Local\Keil_v5\ARM\RV31\Lib
SET CPU_TYPE=LPC1768
SET CPU_VENDOR=NXP (founded by Philips)
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x00B71B00
"C:\users\rahulba\AppData\Local\Keil_v5\ARM\BIN41\ArmCC"  -Via ".\hex\iotest.__i"
